class Commands:
    LEECH = "leech@unnamedKKbot"
    PURGE = "purge@unnamedKKbot"
    PAUSEALL = "pauseall@unnamedKKbot"
    RESUMEALL = "resumeall@unnamedKKbot"
    STATUS = "status@unnamedKKbot"
    SETTINGS = "settings@unnamedKKbot"
    EXEC = "exec@unnamedKKbot"
    UPLOAD = "upload@unnamedKKbot"
    YTDL = "ytdl@unnamedKKbot"
    PYTDL = "pytdl@unnamedKKbot"
    ABOUT = "about@unnamedKKbot"
    GETLOGS = "getlogs@unnamedKKbot"
    SERVER = "server@unnamedKKbot"
    USERSETTINGS = "usetting@unnamedKKbot"
    INSTADL = "instadl@unnamedKKbot"
